# Generated by Django 4.0.4 on 2022-05-18 05:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_strid', models.CharField(max_length=30)),
                ('u_pw', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=20)),
                ('u_phone', models.CharField(blank=True, max_length=20)),
                ('u_date', models.DateTimeField(auto_now_add=True)),
                ('u_drop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=20)),
                ('pet_type', models.CharField(default='강아지', max_length=20)),
                ('pet_breed', models.CharField(max_length=20)),
                ('pet_bcs', models.CharField(max_length=10)),
                ('pet_birthYear', models.CharField(max_length=10)),
                ('pet_birthMonth', models.CharField(max_length=10)),
                ('pet_birthDay', models.CharField(max_length=10)),
                ('pet_weight', models.CharField(max_length=10)),
                ('pet_sex', models.CharField(max_length=10)),
                ('pet_neu', models.CharField(max_length=10)),
                ('pet_alg', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('pet_health', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('pet_petfood', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
