# Generated by Django 4.0.4 on 2022-05-24 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0002_userorder_uo_address2_userorder_uo_address3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uo_address1', models.CharField(blank=True, max_length=20)),
                ('uo_address2', models.CharField(blank=True, max_length=50)),
                ('uo_address3', models.CharField(blank=True, max_length=50)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='userorderdetail',
            name='uo_id',
        ),
        migrations.AddField(
            model_name='userorderdetail',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='userorderdetail',
            name='uod_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
