# Generated by Django 4.0.4 on 2022-05-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonUserOrder',
            fields=[
                ('nuo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nuo_date', models.DateTimeField(auto_now_add=True)),
                ('nuo_address1', models.CharField(max_length=50)),
                ('nuo_name', models.CharField(max_length=20)),
                ('num_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NonUserOrderDetail',
            fields=[
                ('nuod_id', models.AutoField(primary_key=True, serialize=False)),
                ('nuod_count', models.IntegerField(default=1)),
                ('nuod_status', models.CharField(default='주문', max_length=10)),
                ('nuo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.nonuserorder')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('uo_id', models.AutoField(primary_key=True, serialize=False)),
                ('uo_date', models.DateTimeField(auto_now_add=True)),
                ('uo_address1', models.CharField(max_length=50)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRefund',
            fields=[
                ('nur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nur_reason', models.CharField(max_length=300)),
                ('nuod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.nonuserorderdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrderDetail',
            fields=[
                ('uod_id', models.AutoField(primary_key=True, serialize=False)),
                ('uod_count', models.IntegerField(default=1)),
                ('uod_status', models.CharField(default='주문', max_length=10)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('uo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.userorder')),
            ],
        ),
    ]
