# Generated by Django 4.0.4 on 2022-05-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_brand',
        ),
    ]
